In [104]:
import numpy as np

In [105]:
a=np.random.randint(1,10,size=(8))

In [106]:
a

array([3, 5, 9, 4, 7, 2, 2, 6])

In [107]:
a.ndim

1

In [108]:
np.where(a%2==0)

(array([3, 5, 6, 7], dtype=int64),)

In [109]:
np.where(a%2)

(array([0, 1, 2, 4], dtype=int64),)

# Where returns the Index number of items

In [110]:
a=np.random.randint(1,10,size=(8,2))

In [111]:
a

array([[6, 5],
       [7, 4],
       [8, 9],
       [3, 4],
       [7, 8],
       [5, 7],
       [5, 2],
       [6, 8]])

In [112]:
a.ndim

2

In [113]:
np.where(a%2==0)

(array([0, 1, 2, 3, 4, 6, 7, 7], dtype=int64),
 array([0, 1, 0, 1, 1, 1, 0, 1], dtype=int64))

In [114]:
np.where(a)

(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7], dtype=int64),
 array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [115]:
np.where(a+2)

(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7], dtype=int64),
 array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [116]:
np.where(a*2)

(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7], dtype=int64),
 array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [117]:
np.where(a/2)

(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7], dtype=int64),
 array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [118]:
np.where(a//2)

(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7], dtype=int64),
 array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [119]:
np.where(a%2)

(array([0, 1, 2, 3, 4, 5, 5, 6], dtype=int64),
 array([1, 0, 1, 0, 0, 0, 1, 0], dtype=int64))