In [4]:
import numpy as np

In [5]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [6]:
a=np.array(5)

In [7]:
a

array(5)

In [8]:
a.ndim

0

In [168]:
a=np.array((1,2,3,4,5,6,7))

In [169]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [170]:
a.ndim

1

In [171]:
a=np.array(((1,2,3,4,5),(6,7,8,9,10)))

In [172]:
a.ndim

2

In [173]:
a=np.array(((1,2,3,4,5),(6,7,8)))

C:\Users\Admin\AppData\Local\Temp\ipykernel_7280\735488343.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array(((1,2,3,4,5),(6,7,8)))


In [174]:
a

array([(1, 2, 3, 4, 5), (6, 7, 8)], dtype=object)

In [175]:
a.dtype

dtype('O')

In [176]:
a=np.array((1,2,3,4,5,6,7))

In [177]:
a.dtype

dtype('int32')

In [178]:
a=np.array(((1,2,3,4,5),(6,7,8,9,10)))

In [179]:
a.dtype

dtype('int32')

In [180]:
a=np.array(('djj','drr','dkk'))

In [181]:
a.dtype

dtype('<U3')

In [182]:
a=np.array((1,2,3.4,5,6,7))

In [183]:
a

array([1. , 2. , 3.4, 5. , 6. , 7. ])

In [184]:
a.dtype

dtype('float64')

In [185]:
a.itemsize

8

In [186]:
a=np.array((1,2,3,4))

In [187]:
a.itemsize

4

In [188]:
b=np.arange(5)

In [189]:
b

array([0, 1, 2, 3, 4])

In [190]:
b=np.arange(5,100,10)

In [191]:
b

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [192]:
b.shape

(10,)

In [193]:
a=np.array(((1,2,3,4,5),(6,7,8,9,10)))

In [194]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [195]:
a.shape

(2, 5)

In [196]:
a=np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]))

In [197]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [198]:
a.shape

(3, 5)

In [199]:
a.ndim

2

In [200]:
a.dtype

dtype('int32')

In [201]:
a.reshape( 1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [202]:
b=a.reshape(15,1)

In [203]:
b

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [204]:
c=b[0:5,0]

In [205]:
c

array([1, 2, 3, 4, 5])

In [206]:
d=c*10

In [207]:
d

array([10, 20, 30, 40, 50])

In [208]:
c=b[::2]

In [209]:
c

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15]])

In [210]:
c+10

array([[11],
       [13],
       [15],
       [17],
       [19],
       [21],
       [23],
       [25]])

In [211]:
c**2

array([[  1],
       [  9],
       [ 25],
       [ 49],
       [ 81],
       [121],
       [169],
       [225]])

In [212]:
a=np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]))

In [213]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [214]:
c=a[2,1:3]

In [215]:
c

array([12, 13])

In [216]:
c=a[::2,::2]

In [217]:
c

array([[ 1,  3,  5],
       [11, 13, 15]])

In [218]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [219]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [220]:
np.cbrt(a)

array([[1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595],
       [1.81712059, 1.91293118, 2.        , 2.08008382, 2.15443469],
       [2.22398009, 2.28942849, 2.35133469, 2.41014226, 2.46621207]])

In [221]:
np.sum(c)

48

In [222]:
c.sum()

48

In [223]:
c.sum(axis=0)

array([12, 16, 20])

In [224]:
c.sum(axis=1)

array([ 9, 39])

In [225]:
b=np.array(([1,2,3],[4,5,6,7,8]))

C:\Users\Admin\AppData\Local\Temp\ipykernel_7280\1524801184.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array(([1,2,3],[4,5,6,7,8]))


In [226]:
b

array([list([1, 2, 3]), list([4, 5, 6, 7, 8])], dtype=object)

In [227]:
b.ndim

1

In [228]:
d=np.array(([1,2,3],[4,5,6]))
e=np.array(([1,2,3],[4,5,6]))

In [229]:
d+e

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [230]:
np.stack((d,e))

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [231]:
np.stack((d,e),axis=0)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [232]:
f=np.stack((d,e),axis=1)

In [233]:
f

array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6]]])

In [234]:
f.shape

(2, 2, 3)

In [235]:
np.hstack((d,e)).shape

(2, 6)

In [236]:
np.vstack((d,e))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [237]:
np.vstack((d,e),axis=0)

TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'axis'

In [238]:
np.dstack((d,e))

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

In [239]:
np.concatenate((d,e))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [240]:
np.concatenate((d,e),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [241]:
np.concatenate((d,e),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [242]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [243]:
np.array_split(d,10)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32)]

In [244]:
k=np.array(([1,2,3,4],[1,2,3,4],[1,2,3,4]))

In [245]:
k

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [163]:
np.where(k==2)

(array([0, 1, 2], dtype=int64), array([1, 1, 1], dtype=int64))