In [63]:
import numpy as np
import pandas as pd

In [64]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [65]:
np.random.randint(50,300,size=15)

array([ 86,  62,  90, 266, 232, 123, 165, 180, 288, 207, 145, 255, 284,
       146, 293])

In [66]:
np.random.randint(50,150,size=15)

array([ 90, 116,  68, 116, 130, 132, 101,  57, 129,  83, 117, 100,  91,
       125,  76])

In [67]:
x={'days':[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
  'customers':[239, 183, 101, 174, 243, 203,  99,  61, 295, 213, 181, 141,  65,
       264, 222],
  'sold':[124, 127,  85,  86,  82,  59, 107,  50, 103, 107, 104, 136, 102,
        64, 100]}

In [68]:
x

{'days': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
 'customers': [239,
  183,
  101,
  174,
  243,
  203,
  99,
  61,
  295,
  213,
  181,
  141,
  65,
  264,
  222],
 'sold': [124, 127, 85, 86, 82, 59, 107, 50, 103, 107, 104, 136, 102, 64, 100]}

In [69]:
#dataframe

In [70]:
y=pd.DataFrame(x)

In [71]:
y

days  customers  sold
0      1        239   124
1      2        183   127
2      3        101    85
3      4        174    86
4      5        243    82
5      6        203    59
6      7         99   107
7      8         61    50
8      9        295   103
9     10        213   107
10    11        181   104
11    12        141   136
12    13         65   102
13    14        264    64
14    15        222   100

In [72]:
y.shape

(15, 3)

In [73]:
y.columns

Index(['days', 'customers', 'sold'], dtype='object')

In [74]:
y.values

array([[  1, 239, 124],
       [  2, 183, 127],
       [  3, 101,  85],
       [  4, 174,  86],
       [  5, 243,  82],
       [  6, 203,  59],
       [  7,  99, 107],
       [  8,  61,  50],
       [  9, 295, 103],
       [ 10, 213, 107],
       [ 11, 181, 104],
       [ 12, 141, 136],
       [ 13,  65, 102],
       [ 14, 264,  64],
       [ 15, 222, 100]], dtype=int64)

In [75]:
y.size

45

In [76]:
#-- incorporated-numpy scipy matpolotlib

In [77]:
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   days       15 non-null     int64
 1   customers  15 non-null     int64
 2   sold       15 non-null     int64
dtypes: int64(3)
memory usage: 488.0 bytes


In [78]:
y.head()

days  customers  sold
0     1        239   124
1     2        183   127
2     3        101    85
3     4        174    86
4     5        243    82

In [79]:
y.head(5)

days  customers  sold
0     1        239   124
1     2        183   127
2     3        101    85
3     4        174    86
4     5        243    82

In [80]:
y.head(7) #counts

days  customers  sold
0     1        239   124
1     2        183   127
2     3        101    85
3     4        174    86
4     5        243    82
5     6        203    59
6     7         99   107

In [81]:
y.tail()

days  customers  sold
10    11        181   104
11    12        141   136
12    13         65   102
13    14        264    64
14    15        222   100

In [82]:
y.tail(2)

days  customers  sold
13    14        264    64
14    15        222   100

In [83]:
y.tail(15)

days  customers  sold
0      1        239   124
1      2        183   127
2      3        101    85
3      4        174    86
4      5        243    82
5      6        203    59
6      7         99   107
7      8         61    50
8      9        295   103
9     10        213   107
10    11        181   104
11    12        141   136
12    13         65   102
13    14        264    64
14    15        222   100

In [84]:
y

days  customers  sold
0      1        239   124
1      2        183   127
2      3        101    85
3      4        174    86
4      5        243    82
5      6        203    59
6      7         99   107
7      8         61    50
8      9        295   103
9     10        213   107
10    11        181   104
11    12        141   136
12    13         65   102
13    14        264    64
14    15        222   100

In [85]:
y.iloc[3]

days           4
customers    174
sold          86
Name: 3, dtype: int64

In [86]:
y.loc[3]

days           4
customers    174
sold          86
Name: 3, dtype: int64

In [87]:
y.iloc[3:5]

days  customers  sold
3     4        174    86
4     5        243    82

In [88]:
y['sold']

0     124
1     127
2      85
3      86
4      82
5      59
6     107
7      50
8     103
9     107
10    104
11    136
12    102
13     64
14    100
Name: sold, dtype: int64

In [89]:
max(y['sold'])

136

In [90]:
y[y['sold']==max(y['sold'])]

days  customers  sold
11    12        141   136

In [91]:
y[y['sold']==min(y['sold'])]

days  customers  sold
7     8         61    50

In [93]:
y[y['sold']>100]

days  customers  sold
0      1        239   124
1      2        183   127
6      7         99   107
8      9        295   103
9     10        213   107
10    11        181   104
11    12        141   136
12    13         65   102

In [94]:
y[y['sold']<100][y['sold']>75]

C:\Users\Admin\AppData\Local\Temp\ipykernel_8992\2484805876.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  y[y['sold']<100][y['sold']>75]


days  customers  sold
2     3        101    85
3     4        174    86
4     5        243    82

In [95]:
y[y['customers']>150][y['customers']<250]

C:\Users\Admin\AppData\Local\Temp\ipykernel_8992\2612159473.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  y[y['customers']>150][y['customers']<250]


days  customers  sold
0      1        239   124
1      2        183   127
3      4        174    86
4      5        243    82
5      6        203    59
9     10        213   107
10    11        181   104
14    15        222   100

In [96]:
np.random.randint(500,1501,size=15)

array([1122,  948, 1024,  622,  530,  763,  595,  826,  546,  510, 1264,
       1209,  974,  707, 1018])

In [97]:
np.random.randint(1000,3000,size=15)

array([2044, 1958, 2457, 1640, 2654, 2539, 1852, 1597, 2857, 2431, 1429,
       2404, 1346, 1866, 1302])

In [98]:
a={'outcome':[1406,  740,  624, 1130,  870,  858, 1426,  797,  568, 1107, 1225,
        845,  675,  843, 1174],'income':[2947, 2137, 2143, 2177, 2606, 1410, 1921, 1980, 1875, 2250, 2390,
       1636, 2349, 1652, 2891]}

In [99]:
a

{'outcome': [1406,
  740,
  624,
  1130,
  870,
  858,
  1426,
  797,
  568,
  1107,
  1225,
  845,
  675,
  843,
  1174],
 'income': [2947,
  2137,
  2143,
  2177,
  2606,
  1410,
  1921,
  1980,
  1875,
  2250,
  2390,
  1636,
  2349,
  1652,
  2891]}

In [100]:
b=pd.DataFrame(a)

In [101]:
b

outcome  income
0      1406    2947
1       740    2137
2       624    2143
3      1130    2177
4       870    2606
5       858    1410
6      1426    1921
7       797    1980
8       568    1875
9      1107    2250
10     1225    2390
11      845    1636
12      675    2349
13      843    1652
14     1174    2891

In [102]:
joindata=y.join(b)

In [103]:
joindata

days  customers  sold  outcome  income
0      1        239   124     1406    2947
1      2        183   127      740    2137
2      3        101    85      624    2143
3      4        174    86     1130    2177
4      5        243    82      870    2606
5      6        203    59      858    1410
6      7         99   107     1426    1921
7      8         61    50      797    1980
8      9        295   103      568    1875
9     10        213   107     1107    2250
10    11        181   104     1225    2390
11    12        141   136      845    1636
12    13         65   102      675    2349
13    14        264    64      843    1652
14    15        222   100     1174    2891

In [104]:
joindata[joindata['income']==max(joindata['income'])]

days  customers  sold  outcome  income
0     1        239   124     1406    2947

In [105]:
joindata[joindata['income']==min(joindata['income'])]

days  customers  sold  outcome  income
5     6        203    59      858    1410

In [106]:
joindata[joindata['income']<2000][joindata['income']>1500]

C:\Users\Admin\AppData\Local\Temp\ipykernel_8992\2826901194.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  joindata[joindata['income']<2000][joindata['income']>1500]


days  customers  sold  outcome  income
6      7         99   107     1426    1921
7      8         61    50      797    1980
8      9        295   103      568    1875
11    12        141   136      845    1636
13    14        264    64      843    1652